include Make.inc

TARG := mid.a

OFILES :=\
	errstr.o\
	event.o\
	geom.o\
	gfx.o\
	fs.o\
	resrc.o\
	scrn.o\
	snd.o\
	anim.o\
	lvl.o\
	player.o\
	keymap.o\
	enemy.o\
	body.o\
	mem.o\
	item.o\
	env.o\
	zone.o\
	serial.o\
	sword.o\

HFILES :=\
	fs.h\

include Make.lib
