# // Copyright © 2011 Steve McCoy and Ethan Burns
# // Licensed under the MIT License. See LICENSE for details.
include Make.inc

TARG := mid.a

OFILES :=\
	errstr.o\
	event.o\
	keyrpt_sdl$(SDLVER).o\
	geom.o\
	gfx_sdl$(SDLVER).o\
	fs.o\
	resrc.o\
	scrn.o\
	snd.o\
	anim.o\
	lvl.o\
	player.o\
	kbd.o\
	enemy.o\
	body.o\
	mem.o\
	item.o\
	env.o\
	zone.o\
	serial.o\
	sword.o\
	ai.o\
	unti.o\
	nous.o\
	splat.o\
	da.o\
	thu.o\
	grendu.o\
	meter.o\
	armor.o\
	magic.o\

LIBDEPS :=\
	rng

HFILES :=\
	fs.h\
	enemy.h\

include Make.lib
