#!/bin/sh

readflags () {
	ar t $1 | grep -q ldflags && \
	ar -x $1 ldflags && \
	cat ldflags && \
	rm ldflags
	return 0
}

flags=

for f in $@; do
	case $f in
	*.a) flags="$flags `readflags $f`";;
	*) ;;
	esac
done

$@ $flags
