# // Copyright © 2011 Steve McCoy and Ethan Burns
# // Licensed under the MIT License. See LICENSE for details.
include Make.inc

TARG := itmnear

OFILES :=\
	itmnear.o\

LIBDEPS :=\
	mid\
	log\

include Make.cmd
