include ../../Make.inc

TARG := lvlgen
LIB := ../../lib/libmid/libmid.a\
	../../lib/liblog/liblog.a\
	../../lib/librng/librng.a\

OFILES :=\
	lvlgen.o\
	path.o\
	move.o\
	door.o\
	water.o\

HFILES := ../../include/mid.h\
	../../include/log.h\
	../../include/rng.h\
	lvlgen.h\

include ../../Make.cmd
