include ../../Make.inc

TARG := lvlgen
LIB :=\
	../../lib/mid/mid.a\
	../../lib/log/log.a\
	../../lib/rng/rng.a\

OFILES :=\
	lvlgen.o\
	path.o\
	move.o\
	door.o\
	water.o\

HFILES :=\
	../../include/mid.h\
	../../include/log.h\
	../../include/rng.h\
	lvlgen.h\

include ../../Make.cmd
