# // Copyright © 2011 Steve McCoy and Ethan Burns
# // Licensed under the MIT License. See LICENSE for details.
include Make.inc

TARG := lvlgen

OFILES :=\
	lvlgen.o\
	path.o\
	move.o\
	door.o\
	water.o\
	reach.o\

HFILES :=\
	lvlgen.h\

LIBDEPS :=\
	mid\
	log\
	rng\

include Make.cmd
