# // Copyright © 2011 Steve McCoy and Ethan Burns
# // Licensed under the MIT License. See LICENSE for details.
include Make.inc

TARG := envgen

OFILES :=\
	envgen.o\

LIBDEPS :=\
	mid\
	log\
	rng\

include Make.cmd
