# // Copyright © 2011 Steve McCoy and Ethan Burns
# // Licensed under the MIT License. See LICENSE for details.
include ../../Make.inc

TESTS :=\
	rng\

HFILES :=\
	../../include/rng.h\

LIB := ../../lib/librng/librng.a\

include ../../Make.test
