# © 2013 the Mid Authors under the MIT license. See AUTHORS for the list of authors.
include ../../Make.inc

TESTS :=\
	rng\

HFILES :=\
	../../include/rng.h\

LIB := ../../lib/librng/librng.a\

include ../../Make.test
