include ../../Make.inc

TARG := envnear
LIB := ../../lib/libmid/libmid.a\
	../../lib/liblog/liblog.a\

OFILES :=\
	envnear.o\

HFILES := ../../include/mid.h\
	../../include/log.h\

include ../../Make.cmd
