# // Copyright © 2011 Steve McCoy and Ethan Burns
# // Licensed under the MIT License. See LICENSE for details.
include Make.inc

TARG := os.a

OFILES :=\
	dir_$(OS).o\
	pipe_$(OS).o\

HFILES :=\

include Make.lib
