# // Copyright © 2011 Steve McCoy and Ethan Burns
# // Licensed under the MIT License. See LICENSE for details.
DIRS :=\
	mid\
	rectview\
	lvlgen\
	itmnear\
	envgen\
	envnear\
	enmgen\
	enmnear\

include ../Make.dir
