include ../../Make.inc

LIB := libmid.a
OFILES :=\
	errstr.o\
	event.o\
	geom.o\
	gfx.o\
	fs.o\
	resrc.o\
	scrn.o\
	snd.o\
	anim.o\
	lvl.o\
	player.o\
	keymap.o\
	enemy.o\
	body.o\

HFILES :=\
	../../include/mid.h\
	fs.h\

include ../../Make.lib
