# © 2013 the Mid Authors under the MIT license. See AUTHORS for the list of authors.
include ../../Make.inc

TESTS :=\
	fs\
	serial\

HFILES :=\
	../../include/mid.h\
	../../lib/libmid/fs.h\

LIB := ../../lib/libmid/libmid.a\
	../../lib/liblog/liblog.a\

include ../../Make.test
