include ../../Make.inc

TARG := mid
LIB :=\
	../../lib/libmid/libmid.a\
	../../lib/liblog/liblog.a\

OFILES := main.o\
	resrc.o\
	game.o\
	player.o\
	keymap.o\
	inv.o\

HFILES := ../../include/mid.h\
	../../include/log.h\
	resrc.h\
	game.h\

include ../../Make.cmd
