include Make.inc

TARG := mid

OFILES :=\
	main.o\
	game.o\
	invscr.o\
	title.o\
	zone.o\
	statscrn.o\
	death.o\
	cmdpath_$(OS).o\
	optscrn.o\

HFILES :=\
	game.h\

LIBDEPS :=\
	mid\
	log\
	rng\
	os\

include Make.cmd
