# // Copyright © 2011 Steve McCoy and Ethan Burns
# // Licensed under the MIT License. See LICENSE for details.
include Make.inc

TARG := enmnear

OFILES :=\
	enmnear.o\

LIBDEPS :=\
	mid\
	log\

include Make.cmd
